### ISSUE TITLE
STM regression

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#486] opened 2019-12-18 12:58 UTC
> cardano-cli: ExceptionInLinkedThread ThreadId 10 thread blocked indefinitely in an STM transaction

@ksaric @deepfire

**Comment by deepfire** [comment] 2019-12-18 13:03
`serge/repro` (`8faec9733b6f0578c8a397400c7a2b8bdda6d4a0`) is the rev in `cardano-node` where the following is a reproduction:

```
$ cardano-cli --real-pbft print-genesis-hash --genesis-json configuration/genesis/genesis.json
...
cardano-cli: ExceptionInLinkedThread ThreadId 9 thread blocked indefinitely in an STM transaction
```

That `cardano-node` commit bumps `iohk-monitoring` from `b310a4f0b7a80b54edfb094afd3def9eab035f46` to `0c7a55bb703f44f966e43c48e7ebe30eee6d8a70`.

**Comment by deepfire** [comment] 2019-12-18 14:09
Adding a delay before `runCommand` in `cardano-cli.hs` proceeds "fixes" the race:

```
    liftIO $ do
+      hPutStrLn stderr ("delaying" :: Text)
+      threadDelay 1000000
      hPutStrLn stderr ("calling runCommand" :: Text)
    runCommand finalConfig loggingLayer $ mainCommand co
``

**Comment by deepfire** [comment] 2019-12-18 18:12
Eliminating `Switchboard.mainTraceConditionally` from the switchboard's trace doesn't resolve the deadlock.

**Comment by deepfire** [comment] 2019-12-18 18:38
In addition to the above, not passing any backends to the switchboard's dispatcher helps neither:

```diff
-        let bs = bs2 : bs1 : bs0
+        -- let bs = bs2 : bs1 : bs0
+        let bs = []
```

**Comment by deepfire** [comment] 2019-12-18 19:17
Narrowed down the repro to:
```
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}

import           Prelude (String)
import           Cardano.Config.Logging
import           Cardano.Prelude
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as BSL
import           Text.JSON.Canonical (JSValue(..), parseCanonicalJSON)
import           Cardano.BM.Setup (setupTrace_)
import qualified Cardano.BM.Configuration.Model as Config
import qualified Cardano.BM.Backend.Switchboard as Switchboard

main :: IO ()
main = do
 bytes <- BSL.fromStrict <$> BS.readFile "configuration/mainnet-genesis.json"
 _ :: (Trace IO String, Switchboard.Switchboard String)
   <- flip setupTrace_ "cardano" =<< Config.empty
 Right _ :: Either String JSValue <- pure $! parseCanonicalJSON bytes
 pure ()
```
..and the trigger:
```
[nix-shell:~/cardano-node]$ cabal new-run cardano-cli
Up to date
cardano-cli: ExceptionInLinkedThread ThreadId 7 thread blocked indefinitely in an STM transaction
```

**Comment by deepfire** [comment] 2019-12-18 20:16
Further narrowed the repro:
1. inlined `setupTrace_`
2. empty config

https://github.com/input-output-hk/cardano-node/commit/9e7a451ebf7e4892db613183154ba17688f46425

**Comment by deepfire** [comment] 2019-12-18 20:48
Ok, that's the thing:
```haskell
main :: IO ()
main = do
  bytes <- BSL.fromStrict <$> BS.readFile "configuration/mainnet-genesis.json"
 
 
  queue <- atomically $ TBQ.newTBQueue 2048
  let qProc = do
        nlis <- atomically $ do
                      r <- TBQ.flushTBQueue queue
                      when (null r) retry
                      return r
        res <- mapM (const $ pure True) nlis
        when (and res) $ qProc
  dispatcher <- Async.async qProc

  -- The Async.link is necessary
  Async.link dispatcher

  -- 1. the call to `parseCanonicalJSON` is necessary
  -- 2. the fixing of the result to `JSValue` is similarly necessary
  Right _ :: Either String JSValue <- pure $ parseCanonicalJSON bytes
  pure ()
```

**Comment by deepfire** [comment] 2019-12-18 21:07
So the problem is -- we're never exiting the STM transaction -- unless someone logs something.

**Comment by deepfire** [comment] 2019-12-19 12:17
Proper fix in https://github.com/input-output-hk/iohk-monitoring-framework/pull/493

**Comment by deepfire** [comment] 2019-12-19 15:52
Fix merged.

**Closed by deepfire** 2019-12-19 15:52 UTC
Labels: bug
