### ISSUE TITLE
Transaction Generator

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#400] opened 2019-07-08 09:16 UTC
documentation is in [Transaction Generator](https://github.com/input-output-hk/iohk-monitoring-framework/wiki/Transaction-Generator)

* as an independent executable
* prepares a pool of addresses at startup
* can reuse addresses in sending tx
  - txid?
* paramters to sustain fixed TPS
* no out-of-sequence tx submission
* tx generation should be micro-benchmarked

-----

use case: 
* pay dividend to a number of stakeholders
* pay back to clients

```
  +->  Y1
  |
  |        Y2
  +------>
X |
  +------> Y3
  |
  |
  +->  Yn
```

questions:
* how long does it take? (10^6 tx at 10 TPS)
* how large does the chain grow?
* what is the net/disk throughput?

-----

Luke:

> generators from Cardano ledger executable spec (here, for example: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/byron/ledger/executable-spec/src/Ledger/UTxO/Generators.hs)
> generating and elaborating a valid UTxO and also generating a valid transaction based on that UTxO and applying it: https://github.com/input-output-hk/cardano-ledger/blob/master/cardano-ledger/test/Test/Cardano/Chain/UTxO/ValidationMode.hs#L61

**Comment by ksaric** [comment] 2019-07-18 07:56
The tool for generating txs (removed):
- https://github.com/input-output-hk/cardano-sl/commit/7c83a839f00487f941394bd9686706db5561690e#diff-4982b8c60488fc84cb82977bc6427790
- https://github.com/adinapoli-iohk/dbgen

**Comment by ksaric** [comment] 2019-07-18 08:05
Regression benchmark (run on CI ideally, not on the critical path for CI) - 3 nodes
Stress benchmark - 7 core node, 2 relays

We hope to build a tool that enables experimenting with block size, topology, different number of nodes.

**Comment by ksaric** [comment] 2019-07-18 08:10
The benchmark code that can be used - https://github.com/input-output-hk/cardano-sl/tree/develop/explorer/bench

**Comment by ksaric** [comment] 2019-07-18 08:31
![initial_step](https://user-images.githubusercontent.com/6264437/61442102-406a6f00-a947-11e9-90ab-8e069b51c43d.png)

**Comment by ksaric** [comment] 2019-07-18 08:39
Remove the R code and be able to graph in Haskell:
- http://hackage.haskell.org/package/Chart
- http://hackage.haskell.org/package/diagrams

Works inside Jupyter notebook.

**Comment by ksaric** [comment] 2019-07-22 08:06
If I understood @365andreas properly, one of the current questions is why we cannot reuse the change from a richmen.
Also, it might be the case that we are restricted by the type of transaction we can use now (a single address output).

**Comment by 365andreas** [comment] 2019-07-22 08:09
https://github.com/input-output-hk/ouroboros-network/blob/fb505ac7f90e2ec2f95d190fd1350e109da3b58f/ouroboros-consensus/src/Ouroboros/Consensus/Demo/Byron/Elaborate.hs#L40

The change are considered as transaction fees.

**Comment by 365andreas** [comment] 2019-07-22 13:54
mock implementation will *not* be used

**Comment by 365andreas** [comment] 2019-07-22 13:57
A separate set of keys/addresses from the richmen should be used since it'd make it possible to use a generator on a public testnet on a continuous basis.
So even if we only generated 10 new keys, and started by transferring funds from some input (richmen, test ADA faucet, whatever), that would still give us better separation.

**Comment by 365andreas** [comment] 2019-07-29 22:34
branch: https://github.com/input-output-hk/cardano-node/tree/tx-generator

**Comment by 365andreas** [comment] 2019-07-29 22:35
Info in `README.md` (TODO)

**Comment by CodiePP** [comment] 2019-07-31 11:13
two phases of operation:
1.) distribute initial funds to _n_ UTxO
2.) from available funds select outputs and create Tx to same address (creating new UTxO)

## phase 1:
* can only include approx. 60 outputs in one Tx
* mempools have a limit of 200 Tx, translates to 200 Tx per slot (20 secs) (safe margin: 180)
* preparing 10'000 UTxO: 10000 / 60 / 180 = 1 slot; 1 * 20 s = 20 seconds
* preparing 1'000'000 UTxO: 1000000 / 60 / 180 = 93 slots; 93 * 20 s = 31 minutes

## phase 2:
* can reuse TxOut after 240 secs (12 slots), when certainly included in a block
* @ TPS=10 -> 200 Tx per slot -> more than 12 * 200 Tx available (2400 Tx)
* @ TPS=20 -> 400 Tx per slot -> more than 12 * 400 Tx available (4800 Tx)
* @ TPS=40 -> 800 Tx per slot -> more than 12 * 800 Tx available (9600 Tx)

so with a queue of 10'000 Tx we can go up to TPS 40

**Comment by njd42** [comment] 2019-07-31 11:54
Phase 1:
     target'cardano'tps = ...
     slot'interval             = ....
     cardarno'tx'per'slot = target'cardno'tps * slot'interval
     slots'to'settle          =

**Comment by denisshevchenko** [comment] 2019-08-14 05:12
On Phase 1 we introduced `TxSubmissionTracers`, tracers we need for:

1. Benchmarking observables,
2. Connection establishment observables,
3. Transaction submission observables.

**Comment by denisshevchenko** [comment] 2019-08-15 07:24
On phase 2, we have two separate threads: tx generator and tx submitter. Generator creates transactions (with defined number of "fiscal payments") and writes them in a queue. Submitter reads transactions from a queue and submits them.

**Comment by denisshevchenko** [comment] 2019-09-27 09:16
Tx generator is finished (it's a part of `cardano-cli`). Next improvements will be done in the next issues.

**Closed by denisshevchenko** 2019-09-27 09:16 UTC
Labels: staging
